spring.application.name=usersMicroservice
server.port=8090

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5555/authDb
spring.datasource.username=postgres
spring.datasource.password=@admin123

# Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true