spring.application.name=usersMicroservice
server.port=8090

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5555/userDB
spring.datasource.username=postgres
spring.datasource.password=@admin123

# Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true

spring.redis.host=localhost
spring.redis.port=6379
#spring.redis.password=@admin123
